version: "3"
services:
  lb:
    #image: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    command: [nginx-debug, "-g", "daemon off;"]
    depends_on:
      - app1
      # - app2
      # - app3
  app1:
    #image: node:10
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - SERVER_ID=1
  # app2:
  #   image: app
  #   ports:
  #     - "3002:3002"
  #   environment:
  #     - PORT=3002
  #     - SERVER_ID=1
  # app3:
  #   image: app
  #   ports:
  #     - "3003:3003"
  #   environment:
  #     - PORT=3003
  #     - SERVER_ID=1
